/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import PerfLogger from 'react-native-perf-logger';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  async componentDidMount() {

    PerfLogger.registerTTICompletedListener(async () => {
      const result = await PerfLogger.getMarkersJSON();
      console.log(result);
      this.setState({
        status: 'TTI completed',
        message: 'TTI completed'
      });
    })
  }
  render() {
    return (
      <View style={styles.container} nativeID="tti_complete">
        <Text style={styles.welcome}>☆PerfLogger example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
